version: "3.9"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    volumes:
      - ~/opt/pg_data/sitewomen:/var/lib/postgresql/data
    env_file:
      - .env

  sitewomen:
    image: sitewomen:v01
    container_name: sitewomen
    restart: always
    depends_on:
      - db_postgres
    volumes:
      - static_volume:/sitewomen/static
      - media_volume:/sitewomen/media
    env_file:
      - .env
    command: >
      bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py runserver localhost:8080"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
#    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - sitewomen
    volumes:
      - static_volume:/sitewomen/static
      - media_volume:/sitewomen/media
    ports:
      - "${NGINX_EXTERNAL_PORT}:8080"

volumes:
  static_volume:
  media_volume:
