version: "3.9"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    restart: always
    volumes:
      - /opt/pg_data/sitewomen:/var/lib/postgresql/data
    env_file:
      - .env

  sitewomen:
    build:
      context: .
    container_name: sitewomen
    restart: always
    depends_on:
      - db_postgres
    volumes:
      - static_volume:/sitewomen/static
      - media_volume:/sitewomen/media
    env_file:
      - .env
    command: >
      bash -c "python manage.py collectstatic --noinput \
      && python manage.py migrate --noinput \
      && python manage.py loaddata db.json \
      && gunicorn -b 0.0.0.0:8000 sitewomen.wsgi:application"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    restart: always
    depends_on:
      - sitewomen
    volumes:
      - static_volume:/sitewomen/static
      - media_volume:/sitewomen/media
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
